<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
   <NoWarn>$(NoWarn);NU1901;NU1903</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Uploads\Downloads\Sample-DealerRegistration\SubDealerImportSample_v29.xlsx">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.OpenApi" Version="2.4.1" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.2" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
    <PackageReference Include="NuGet.Packaging" Version="7.6.0" />
    <PackageReference Include="NuGet.Protocol" Version="7.6.0" />
    <PackageReference Include="PDFtoImage" Version="5.2.1" />
    <PackageReference Include="QuestPDF" Version="2026.7.3" />
    <!--<PackageReference Include="Microsoft.Extensions.Http" Version="10.0.5" />-->
    <!--<PackageReference Include="Microsoft.OpenApi" Version="3.5.1" />-->
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
    <!--<PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="10.1.7" />-->
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.17.0" />
    <PackageReference Include="UglyToad.PdfPig" Version="1.7.0-custom-5" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.104.0" />
    <PackageReference Include="Tesseract" Version="5.2.0" />
    <ProjectReference Include="..\SPIC.Core\SPIC.Core.csproj" />
    <ProjectReference Include="..\Spic.Infrastructure\Spic.Infrastructure.csproj" />
  </ItemGroup>

</Project>
