using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace Spic.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class V19AddSatemappingProgram : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // 2026-10-07 (pre-deploy dry run): this migration was scaffolded on a branch without
            // v19JmdoAttendanceTrackingAndPageCatalogue and therefore also created JMDOAttendances /
            // JMDOTrackingSessions / JMDOTrackingPoints. Those tables already exist in production
            // (v19 applied 2026-10-06), so the duplicate CreateTable / CreateIndex / DropTable calls
            // were removed here. Only ProgramStateMappings and its data belong to this migration.

            migrationBuilder.CreateTable(
                name: "ProgramStateMappings",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    ProgramId = table.Column<int>(type: "integer", nullable: false),
                    StateId = table.Column<int>(type: "integer", nullable: false),
                    IsApplicable = table.Column<bool>(type: "boolean", nullable: false),
                    CreatedBy = table.Column<string>(type: "text", nullable: false),
                    UpdatedBy = table.Column<string>(type: "text", nullable: true),
                    CreatedAt = table.Column<DateTime>(type: "timestamp without time zone", nullable: false),
                    UpdatedAt = table.Column<DateTime>(type: "timestamp without time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ProgramStateMappings", x => x.Id);
                    table.ForeignKey(
                        name: "FK_ProgramStateMappings_ProgramMasters_ProgramId",
                        column: x => x.ProgramId,
                        principalTable: "ProgramMasters",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_ProgramStateMappings_States_StateId",
                        column: x => x.StateId,
                        principalTable: "States",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "IX_ProgramStateMappings_ProgramId_StateId",
                table: "ProgramStateMappings",
                columns: new[] { "ProgramId", "StateId" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_ProgramStateMappings_StateId",
                table: "ProgramStateMappings",
                column: "StateId");
            // Initial state-wise applicability from ProgramWiseBudget.csv (44 programs x 11 states
            // = 484 rows; "Yes" -> IsApplicable = true, "No" -> false). Programs are matched to the
            // existing ProgramMasters by Name and states to the existing States by StateName
            // (trimmed, case-insensitive) - no ProgramMasters/States rows are created or modified.
            // CSV entries with no match are skipped and reported via RAISE NOTICE for manual review.
            // 2026-10-07: the dollar quotes of the DO block were "$" instead of "$$" (PostgreSQL
            // syntax error at "$"), fixed on the pre-deploy dry run.
            migrationBuilder.Sql(@"
                CREATE TEMP TABLE ""_ProgramStateCsv"" (""ProgramName"" text, ""StateName"" text, ""IsApplicable"" boolean) ON COMMIT DROP;

                INSERT INTO ""_ProgramStateCsv"" (""ProgramName"", ""StateName"", ""IsApplicable"") VALUES
                    ('Regional Farmers meeting', 'Tamil Nadu', true),
                    ('Regional Farmers meeting', 'Karnataka', true),
                    ('Regional Farmers meeting', 'Kerala', true),
                    ('Regional Farmers meeting', 'Andhra Pradesh', true),
                    ('Regional Farmers meeting', 'Telangana', true),
                    ('Regional Farmers meeting', 'Maharashtra', true),
                    ('Regional Farmers meeting', 'Madhya Pradesh', true),
                    ('Regional Farmers meeting', 'Uttar Pradesh', true),
                    ('Regional Farmers meeting', 'Haryana', true),
                    ('Regional Farmers meeting', 'Bihar', true),
                    ('Regional Farmers meeting', 'West Bengal', true),
                    ('District Farmers meeting', 'Tamil Nadu', true),
                    ('District Farmers meeting', 'Karnataka', true),
                    ('District Farmers meeting', 'Kerala', true),
                    ('District Farmers meeting', 'Andhra Pradesh', true),
                    ('District Farmers meeting', 'Telangana', true),
                    ('District Farmers meeting', 'Maharashtra', true),
                    ('District Farmers meeting', 'Madhya Pradesh', true),
                    ('District Farmers meeting', 'Uttar Pradesh', true),
                    ('District Farmers meeting', 'Haryana', true),
                    ('District Farmers meeting', 'Bihar', true),
                    ('District Farmers meeting', 'West Bengal', true),
                    ('Crop Seminar', 'Tamil Nadu', true),
                    ('Crop Seminar', 'Karnataka', true),
                    ('Crop Seminar', 'Kerala', true),
                    ('Crop Seminar', 'Andhra Pradesh', true),
                    ('Crop Seminar', 'Telangana', true),
                    ('Crop Seminar', 'Maharashtra', true),
                    ('Crop Seminar', 'Madhya Pradesh', true),
                    ('Crop Seminar', 'Uttar Pradesh', true),
                    ('Crop Seminar', 'Haryana', true),
                    ('Crop Seminar', 'Bihar', true),
                    ('Crop Seminar', 'West Bengal', true),
                    ('Farmers Training programme', 'Tamil Nadu', true),
                    ('Farmers Training programme', 'Karnataka', true),
                    ('Farmers Training programme', 'Kerala', true),
                    ('Farmers Training programme', 'Andhra Pradesh', true),
                    ('Farmers Training programme', 'Telangana', true),
                    ('Farmers Training programme', 'Maharashtra', true),
                    ('Farmers Training programme', 'Madhya Pradesh', true),
                    ('Farmers Training programme', 'Uttar Pradesh', true),
                    ('Farmers Training programme', 'Haryana', true),
                    ('Farmers Training programme', 'Bihar', true),
                    ('Farmers Training programme', 'West Bengal', true),
                    ('AV Van Campaign', 'Tamil Nadu', true),
                    ('AV Van Campaign', 'Karnataka', true),
                    ('AV Van Campaign', 'Kerala', false),
                    ('AV Van Campaign', 'Andhra Pradesh', true),
                    ('AV Van Campaign', 'Telangana', true),
                    ('AV Van Campaign', 'Maharashtra', true),
                    ('AV Van Campaign', 'Madhya Pradesh', false),
                    ('AV Van Campaign', 'Uttar Pradesh', false),
                    ('AV Van Campaign', 'Haryana', false),
                    ('AV Van Campaign', 'Bihar', false),
                    ('AV Van Campaign', 'West Bengal', false),
                    ('Squad campaign (Jeep/ Van)', 'Tamil Nadu', false),
                    ('Squad campaign (Jeep/ Van)', 'Karnataka', false),
                    ('Squad campaign (Jeep/ Van)', 'Kerala', true),
                    ('Squad campaign (Jeep/ Van)', 'Andhra Pradesh', false),
                    ('Squad campaign (Jeep/ Van)', 'Telangana', false),
                    ('Squad campaign (Jeep/ Van)', 'Maharashtra', true),
                    ('Squad campaign (Jeep/ Van)', 'Madhya Pradesh', true),
                    ('Squad campaign (Jeep/ Van)', 'Uttar Pradesh', true),
                    ('Squad campaign (Jeep/ Van)', 'Haryana', true),
                    ('Squad campaign (Jeep/ Van)', 'Bihar', true),
                    ('Squad campaign (Jeep/ Van)', 'West Bengal', true),
                    ('Spot Demonstration', 'Tamil Nadu', true),
                    ('Spot Demonstration', 'Karnataka', true),
                    ('Spot Demonstration', 'Kerala', true),
                    ('Spot Demonstration', 'Andhra Pradesh', true),
                    ('Spot Demonstration', 'Telangana', true),
                    ('Spot Demonstration', 'Maharashtra', true),
                    ('Spot Demonstration', 'Madhya Pradesh', true),
                    ('Spot Demonstration', 'Uttar Pradesh', true),
                    ('Spot Demonstration', 'Haryana', true),
                    ('Spot Demonstration', 'Bihar', true),
                    ('Spot Demonstration', 'West Bengal', true),
                    ('Shandy Campaign/ Shandy Display', 'Tamil Nadu', true),
                    ('Shandy Campaign/ Shandy Display', 'Karnataka', true),
                    ('Shandy Campaign/ Shandy Display', 'Kerala', true),
                    ('Shandy Campaign/ Shandy Display', 'Andhra Pradesh', true),
                    ('Shandy Campaign/ Shandy Display', 'Telangana', true),
                    ('Shandy Campaign/ Shandy Display', 'Maharashtra', true),
                    ('Shandy Campaign/ Shandy Display', 'Madhya Pradesh', true),
                    ('Shandy Campaign/ Shandy Display', 'Uttar Pradesh', true),
                    ('Shandy Campaign/ Shandy Display', 'Haryana', true),
                    ('Shandy Campaign/ Shandy Display', 'Bihar', true),
                    ('Shandy Campaign/ Shandy Display', 'West Bengal', true),
                    ('Village Level meeting', 'Tamil Nadu', true),
                    ('Village Level meeting', 'Karnataka', true),
                    ('Village Level meeting', 'Kerala', true),
                    ('Village Level meeting', 'Andhra Pradesh', true),
                    ('Village Level meeting', 'Telangana', true),
                    ('Village Level meeting', 'Maharashtra', true),
                    ('Village Level meeting', 'Madhya Pradesh', true),
                    ('Village Level meeting', 'Uttar Pradesh', true),
                    ('Village Level meeting', 'Haryana', true),
                    ('Village Level meeting', 'Bihar', true),
                    ('Village Level meeting', 'West Bengal', true),
                    ('IFCP', 'Tamil Nadu', false),
                    ('IFCP', 'Karnataka', false),
                    ('IFCP', 'Kerala', false),
                    ('IFCP', 'Andhra Pradesh', false),
                    ('IFCP', 'Telangana', false),
                    ('IFCP', 'Maharashtra', true),
                    ('IFCP', 'Madhya Pradesh', true),
                    ('IFCP', 'Uttar Pradesh', true),
                    ('IFCP', 'Haryana', true),
                    ('IFCP', 'Bihar', true),
                    ('IFCP', 'West Bengal', true),
                    ('Elite Dealers Family Meet', 'Tamil Nadu', true),
                    ('Elite Dealers Family Meet', 'Karnataka', true),
                    ('Elite Dealers Family Meet', 'Kerala', true),
                    ('Elite Dealers Family Meet', 'Andhra Pradesh', true),
                    ('Elite Dealers Family Meet', 'Telangana', true),
                    ('Elite Dealers Family Meet', 'Maharashtra', true),
                    ('Elite Dealers Family Meet', 'Madhya Pradesh', true),
                    ('Elite Dealers Family Meet', 'Uttar Pradesh', true),
                    ('Elite Dealers Family Meet', 'Haryana', true),
                    ('Elite Dealers Family Meet', 'Bihar', true),
                    ('Elite Dealers Family Meet', 'West Bengal', true),
                    ('Dealers Meet - State Level', 'Tamil Nadu', true),
                    ('Dealers Meet - State Level', 'Karnataka', true),
                    ('Dealers Meet - State Level', 'Kerala', true),
                    ('Dealers Meet - State Level', 'Andhra Pradesh', true),
                    ('Dealers Meet - State Level', 'Telangana', true),
                    ('Dealers Meet - State Level', 'Maharashtra', true),
                    ('Dealers Meet - State Level', 'Madhya Pradesh', true),
                    ('Dealers Meet - State Level', 'Uttar Pradesh', true),
                    ('Dealers Meet - State Level', 'Haryana', true),
                    ('Dealers Meet - State Level', 'Bihar', true),
                    ('Dealers Meet - State Level', 'West Bengal', true),
                    ('Dealers Meet - Regional Level', 'Tamil Nadu', true),
                    ('Dealers Meet - Regional Level', 'Karnataka', true),
                    ('Dealers Meet - Regional Level', 'Kerala', true),
                    ('Dealers Meet - Regional Level', 'Andhra Pradesh', true),
                    ('Dealers Meet - Regional Level', 'Telangana', true),
                    ('Dealers Meet - Regional Level', 'Maharashtra', true),
                    ('Dealers Meet - Regional Level', 'Madhya Pradesh', true),
                    ('Dealers Meet - Regional Level', 'Uttar Pradesh', true),
                    ('Dealers Meet - Regional Level', 'Haryana', true),
                    ('Dealers Meet - Regional Level', 'Bihar', true),
                    ('Dealers Meet - Regional Level', 'West Bengal', true),
                    ('Sub Dealers Training programme', 'Tamil Nadu', true),
                    ('Sub Dealers Training programme', 'Karnataka', true),
                    ('Sub Dealers Training programme', 'Kerala', true),
                    ('Sub Dealers Training programme', 'Andhra Pradesh', true),
                    ('Sub Dealers Training programme', 'Telangana', true),
                    ('Sub Dealers Training programme', 'Maharashtra', true),
                    ('Sub Dealers Training programme', 'Madhya Pradesh', true),
                    ('Sub Dealers Training programme', 'Uttar Pradesh', true),
                    ('Sub Dealers Training programme', 'Haryana', true),
                    ('Sub Dealers Training programme', 'Bihar', true),
                    ('Sub Dealers Training programme', 'West Bengal', true),
                    ('Plant Visit', 'Tamil Nadu', false),
                    ('Plant Visit', 'Karnataka', true),
                    ('Plant Visit', 'Kerala', true),
                    ('Plant Visit', 'Andhra Pradesh', true),
                    ('Plant Visit', 'Telangana', true),
                    ('Plant Visit', 'Maharashtra', true),
                    ('Plant Visit', 'Madhya Pradesh', true),
                    ('Plant Visit', 'Uttar Pradesh', true),
                    ('Plant Visit', 'Haryana', true),
                    ('Plant Visit', 'Bihar', true),
                    ('Plant Visit', 'West Bengal', true),
                    ('Plant Visit - TN', 'Tamil Nadu', true),
                    ('Plant Visit - TN', 'Karnataka', false),
                    ('Plant Visit - TN', 'Kerala', false),
                    ('Plant Visit - TN', 'Andhra Pradesh', false),
                    ('Plant Visit - TN', 'Telangana', false),
                    ('Plant Visit - TN', 'Maharashtra', false),
                    ('Plant Visit - TN', 'Madhya Pradesh', false),
                    ('Plant Visit - TN', 'Uttar Pradesh', false),
                    ('Plant Visit - TN', 'Haryana', false),
                    ('Plant Visit - TN', 'Bihar', false),
                    ('Plant Visit - TN', 'West Bengal', false),
                    ('Shop-men Training programme', 'Tamil Nadu', true),
                    ('Shop-men Training programme', 'Karnataka', true),
                    ('Shop-men Training programme', 'Kerala', true),
                    ('Shop-men Training programme', 'Andhra Pradesh', true),
                    ('Shop-men Training programme', 'Telangana', true),
                    ('Shop-men Training programme', 'Maharashtra', true),
                    ('Shop-men Training programme', 'Madhya Pradesh', true),
                    ('Shop-men Training programme', 'Uttar Pradesh', true),
                    ('Shop-men Training programme', 'Haryana', true),
                    ('Shop-men Training programme', 'Bihar', true),
                    ('Shop-men Training programme', 'West Bengal', true),
                    ('Spray-men Training programme', 'Tamil Nadu', true),
                    ('Spray-men Training programme', 'Karnataka', true),
                    ('Spray-men Training programme', 'Kerala', true),
                    ('Spray-men Training programme', 'Andhra Pradesh', true),
                    ('Spray-men Training programme', 'Telangana', true),
                    ('Spray-men Training programme', 'Maharashtra', true),
                    ('Spray-men Training programme', 'Madhya Pradesh', true),
                    ('Spray-men Training programme', 'Uttar Pradesh', true),
                    ('Spray-men Training programme', 'Haryana', true),
                    ('Spray-men Training programme', 'Bihar', true),
                    ('Spray-men Training programme', 'West Bengal', true),
                    ('Display Contest', 'Tamil Nadu', true),
                    ('Display Contest', 'Karnataka', true),
                    ('Display Contest', 'Kerala', true),
                    ('Display Contest', 'Andhra Pradesh', true),
                    ('Display Contest', 'Telangana', true),
                    ('Display Contest', 'Maharashtra', true),
                    ('Display Contest', 'Madhya Pradesh', true),
                    ('Display Contest', 'Uttar Pradesh', true),
                    ('Display Contest', 'Haryana', true),
                    ('Display Contest', 'Bihar', true),
                    ('Display Contest', 'West Bengal', true),
                    ('Mystery Customer', 'Tamil Nadu', true),
                    ('Mystery Customer', 'Karnataka', true),
                    ('Mystery Customer', 'Kerala', true),
                    ('Mystery Customer', 'Andhra Pradesh', true),
                    ('Mystery Customer', 'Telangana', true),
                    ('Mystery Customer', 'Maharashtra', true),
                    ('Mystery Customer', 'Madhya Pradesh', true),
                    ('Mystery Customer', 'Uttar Pradesh', true),
                    ('Mystery Customer', 'Haryana', true),
                    ('Mystery Customer', 'Bihar', true),
                    ('Mystery Customer', 'West Bengal', true),
                    ('Programme with Dept of Agri./ Univ./ RS/ FAI/ SICCI', 'Tamil Nadu', true),
                    ('Programme with Dept of Agri./ Univ./ RS/ FAI/ SICCI', 'Karnataka', true),
                    ('Programme with Dept of Agri./ Univ./ RS/ FAI/ SICCI', 'Kerala', true),
                    ('Programme with Dept of Agri./ Univ./ RS/ FAI/ SICCI', 'Andhra Pradesh', true),
                    ('Programme with Dept of Agri./ Univ./ RS/ FAI/ SICCI', 'Telangana', true),
                    ('Programme with Dept of Agri./ Univ./ RS/ FAI/ SICCI', 'Maharashtra', true),
                    ('Programme with Dept of Agri./ Univ./ RS/ FAI/ SICCI', 'Madhya Pradesh', true),
                    ('Programme with Dept of Agri./ Univ./ RS/ FAI/ SICCI', 'Uttar Pradesh', true),
                    ('Programme with Dept of Agri./ Univ./ RS/ FAI/ SICCI', 'Haryana', true),
                    ('Programme with Dept of Agri./ Univ./ RS/ FAI/ SICCI', 'Bihar', true),
                    ('Programme with Dept of Agri./ Univ./ RS/ FAI/ SICCI', 'West Bengal', true),
                    ('FEDERATIONS', 'Tamil Nadu', true),
                    ('FEDERATIONS', 'Karnataka', true),
                    ('FEDERATIONS', 'Kerala', true),
                    ('FEDERATIONS', 'Andhra Pradesh', true),
                    ('FEDERATIONS', 'Telangana', true),
                    ('FEDERATIONS', 'Maharashtra', true),
                    ('FEDERATIONS', 'Madhya Pradesh', true),
                    ('FEDERATIONS', 'Uttar Pradesh', true),
                    ('FEDERATIONS', 'Haryana', true),
                    ('FEDERATIONS', 'Bihar', true),
                    ('FEDERATIONS', 'West Bengal', true),
                    ('Exhibition (Incidental expenses)', 'Tamil Nadu', true),
                    ('Exhibition (Incidental expenses)', 'Karnataka', true),
                    ('Exhibition (Incidental expenses)', 'Kerala', true),
                    ('Exhibition (Incidental expenses)', 'Andhra Pradesh', true),
                    ('Exhibition (Incidental expenses)', 'Telangana', true),
                    ('Exhibition (Incidental expenses)', 'Maharashtra', true),
                    ('Exhibition (Incidental expenses)', 'Madhya Pradesh', true),
                    ('Exhibition (Incidental expenses)', 'Uttar Pradesh', true),
                    ('Exhibition (Incidental expenses)', 'Haryana', true),
                    ('Exhibition (Incidental expenses)', 'Bihar', true),
                    ('Exhibition (Incidental expenses)', 'West Bengal', true),
                    ('Road show', 'Tamil Nadu', true),
                    ('Road show', 'Karnataka', true),
                    ('Road show', 'Kerala', true),
                    ('Road show', 'Andhra Pradesh', true),
                    ('Road show', 'Telangana', true),
                    ('Road show', 'Maharashtra', true),
                    ('Road show', 'Madhya Pradesh', true),
                    ('Road show', 'Uttar Pradesh', true),
                    ('Road show', 'Haryana', true),
                    ('Road show', 'Bihar', true),
                    ('Road show', 'West Bengal', true),
                    ('Planters Meet/ Participation in AGMs', 'Tamil Nadu', true),
                    ('Planters Meet/ Participation in AGMs', 'Karnataka', true),
                    ('Planters Meet/ Participation in AGMs', 'Kerala', true),
                    ('Planters Meet/ Participation in AGMs', 'Andhra Pradesh', true),
                    ('Planters Meet/ Participation in AGMs', 'Telangana', true),
                    ('Planters Meet/ Participation in AGMs', 'Maharashtra', true),
                    ('Planters Meet/ Participation in AGMs', 'Madhya Pradesh', true),
                    ('Planters Meet/ Participation in AGMs', 'Uttar Pradesh', true),
                    ('Planters Meet/ Participation in AGMs', 'Haryana', true),
                    ('Planters Meet/ Participation in AGMs', 'Bihar', true),
                    ('Planters Meet/ Participation in AGMs', 'West Bengal', true),
                    ('Product Launch Programme', 'Tamil Nadu', true),
                    ('Product Launch Programme', 'Karnataka', true),
                    ('Product Launch Programme', 'Kerala', true),
                    ('Product Launch Programme', 'Andhra Pradesh', true),
                    ('Product Launch Programme', 'Telangana', true),
                    ('Product Launch Programme', 'Maharashtra', true),
                    ('Product Launch Programme', 'Madhya Pradesh', true),
                    ('Product Launch Programme', 'Uttar Pradesh', true),
                    ('Product Launch Programme', 'Haryana', true),
                    ('Product Launch Programme', 'Bihar', true),
                    ('Product Launch Programme', 'West Bengal', true),
                    ('Rural Events/ Festival/ Sports', 'Tamil Nadu', true),
                    ('Rural Events/ Festival/ Sports', 'Karnataka', true),
                    ('Rural Events/ Festival/ Sports', 'Kerala', true),
                    ('Rural Events/ Festival/ Sports', 'Andhra Pradesh', true),
                    ('Rural Events/ Festival/ Sports', 'Telangana', true),
                    ('Rural Events/ Festival/ Sports', 'Maharashtra', true),
                    ('Rural Events/ Festival/ Sports', 'Madhya Pradesh', true),
                    ('Rural Events/ Festival/ Sports', 'Uttar Pradesh', true),
                    ('Rural Events/ Festival/ Sports', 'Haryana', true),
                    ('Rural Events/ Festival/ Sports', 'Bihar', true),
                    ('Rural Events/ Festival/ Sports', 'West Bengal', true),
                    ('Technical Assistants Training programme', 'Tamil Nadu', true),
                    ('Technical Assistants Training programme', 'Karnataka', true),
                    ('Technical Assistants Training programme', 'Kerala', true),
                    ('Technical Assistants Training programme', 'Andhra Pradesh', true),
                    ('Technical Assistants Training programme', 'Telangana', true),
                    ('Technical Assistants Training programme', 'Maharashtra', true),
                    ('Technical Assistants Training programme', 'Madhya Pradesh', true),
                    ('Technical Assistants Training programme', 'Uttar Pradesh', true),
                    ('Technical Assistants Training programme', 'Haryana', true),
                    ('Technical Assistants Training programme', 'Bihar', true),
                    ('Technical Assistants Training programme', 'West Bengal', true),
                    ('Soil sample collection (Transportation cost)', 'Tamil Nadu', true),
                    ('Soil sample collection (Transportation cost)', 'Karnataka', true),
                    ('Soil sample collection (Transportation cost)', 'Kerala', true),
                    ('Soil sample collection (Transportation cost)', 'Andhra Pradesh', true),
                    ('Soil sample collection (Transportation cost)', 'Telangana', true),
                    ('Soil sample collection (Transportation cost)', 'Maharashtra', true),
                    ('Soil sample collection (Transportation cost)', 'Madhya Pradesh', true),
                    ('Soil sample collection (Transportation cost)', 'Uttar Pradesh', true),
                    ('Soil sample collection (Transportation cost)', 'Haryana', true),
                    ('Soil sample collection (Transportation cost)', 'Bihar', true),
                    ('Soil sample collection (Transportation cost)', 'West Bengal', true),
                    ('AV Van - Temporary driver', 'Tamil Nadu', true),
                    ('AV Van - Temporary driver', 'Karnataka', true),
                    ('AV Van - Temporary driver', 'Kerala', false),
                    ('AV Van - Temporary driver', 'Andhra Pradesh', true),
                    ('AV Van - Temporary driver', 'Telangana', true),
                    ('AV Van - Temporary driver', 'Maharashtra', true),
                    ('AV Van - Temporary driver', 'Madhya Pradesh', false),
                    ('AV Van - Temporary driver', 'Uttar Pradesh', false),
                    ('AV Van - Temporary driver', 'Haryana', false),
                    ('AV Van - Temporary driver', 'Bihar', false),
                    ('AV Van - Temporary driver', 'West Bengal', false),
                    ('News Paper Ad', 'Tamil Nadu', true),
                    ('News Paper Ad', 'Karnataka', true),
                    ('News Paper Ad', 'Kerala', true),
                    ('News Paper Ad', 'Andhra Pradesh', true),
                    ('News Paper Ad', 'Telangana', true),
                    ('News Paper Ad', 'Maharashtra', true),
                    ('News Paper Ad', 'Madhya Pradesh', true),
                    ('News Paper Ad', 'Uttar Pradesh', true),
                    ('News Paper Ad', 'Haryana', true),
                    ('News Paper Ad', 'Bihar', true),
                    ('News Paper Ad', 'West Bengal', true),
                    ('Advt. in Agricultural Magazines', 'Tamil Nadu', true),
                    ('Advt. in Agricultural Magazines', 'Karnataka', true),
                    ('Advt. in Agricultural Magazines', 'Kerala', true),
                    ('Advt. in Agricultural Magazines', 'Andhra Pradesh', true),
                    ('Advt. in Agricultural Magazines', 'Telangana', true),
                    ('Advt. in Agricultural Magazines', 'Maharashtra', true),
                    ('Advt. in Agricultural Magazines', 'Madhya Pradesh', true),
                    ('Advt. in Agricultural Magazines', 'Uttar Pradesh', true),
                    ('Advt. in Agricultural Magazines', 'Haryana', true),
                    ('Advt. in Agricultural Magazines', 'Bihar', true),
                    ('Advt. in Agricultural Magazines', 'West Bengal', true),
                    ('TV Advertisement - Time Ticker', 'Tamil Nadu', true),
                    ('TV Advertisement - Time Ticker', 'Karnataka', true),
                    ('TV Advertisement - Time Ticker', 'Kerala', true),
                    ('TV Advertisement - Time Ticker', 'Andhra Pradesh', true),
                    ('TV Advertisement - Time Ticker', 'Telangana', true),
                    ('TV Advertisement - Time Ticker', 'Maharashtra', true),
                    ('TV Advertisement - Time Ticker', 'Madhya Pradesh', true),
                    ('TV Advertisement - Time Ticker', 'Uttar Pradesh', true),
                    ('TV Advertisement - Time Ticker', 'Haryana', true),
                    ('TV Advertisement - Time Ticker', 'Bihar', true),
                    ('TV Advertisement - Time Ticker', 'West Bengal', true),
                    ('TV Advertisement - Film Production', 'Tamil Nadu', true),
                    ('TV Advertisement - Film Production', 'Karnataka', true),
                    ('TV Advertisement - Film Production', 'Kerala', true),
                    ('TV Advertisement - Film Production', 'Andhra Pradesh', true),
                    ('TV Advertisement - Film Production', 'Telangana', true),
                    ('TV Advertisement - Film Production', 'Maharashtra', true),
                    ('TV Advertisement - Film Production', 'Madhya Pradesh', true),
                    ('TV Advertisement - Film Production', 'Uttar Pradesh', true),
                    ('TV Advertisement - Film Production', 'Haryana', true),
                    ('TV Advertisement - Film Production', 'Bihar', true),
                    ('TV Advertisement - Film Production', 'West Bengal', true),
                    ('TV Ad Screening charges', 'Tamil Nadu', true),
                    ('TV Ad Screening charges', 'Karnataka', true),
                    ('TV Ad Screening charges', 'Kerala', true),
                    ('TV Ad Screening charges', 'Andhra Pradesh', true),
                    ('TV Ad Screening charges', 'Telangana', true),
                    ('TV Ad Screening charges', 'Maharashtra', true),
                    ('TV Ad Screening charges', 'Madhya Pradesh', true),
                    ('TV Ad Screening charges', 'Uttar Pradesh', true),
                    ('TV Ad Screening charges', 'Haryana', true),
                    ('TV Ad Screening charges', 'Bihar', true),
                    ('TV Ad Screening charges', 'West Bengal', true),
                    ('FM radio', 'Tamil Nadu', true),
                    ('FM radio', 'Karnataka', true),
                    ('FM radio', 'Kerala', true),
                    ('FM radio', 'Andhra Pradesh', true),
                    ('FM radio', 'Telangana', true),
                    ('FM radio', 'Maharashtra', true),
                    ('FM radio', 'Madhya Pradesh', true),
                    ('FM radio', 'Uttar Pradesh', true),
                    ('FM radio', 'Haryana', true),
                    ('FM radio', 'Bihar', true),
                    ('FM radio', 'West Bengal', true),
                    ('Radio jingles - Production Cost', 'Tamil Nadu', true),
                    ('Radio jingles - Production Cost', 'Karnataka', true),
                    ('Radio jingles - Production Cost', 'Kerala', true),
                    ('Radio jingles - Production Cost', 'Andhra Pradesh', true),
                    ('Radio jingles - Production Cost', 'Telangana', true),
                    ('Radio jingles - Production Cost', 'Maharashtra', true),
                    ('Radio jingles - Production Cost', 'Madhya Pradesh', true),
                    ('Radio jingles - Production Cost', 'Uttar Pradesh', true),
                    ('Radio jingles - Production Cost', 'Haryana', true),
                    ('Radio jingles - Production Cost', 'Bihar', true),
                    ('Radio jingles - Production Cost', 'West Bengal', true),
                    ('Radio Talk with Farmer', 'Tamil Nadu', true),
                    ('Radio Talk with Farmer', 'Karnataka', true),
                    ('Radio Talk with Farmer', 'Kerala', true),
                    ('Radio Talk with Farmer', 'Andhra Pradesh', true),
                    ('Radio Talk with Farmer', 'Telangana', true),
                    ('Radio Talk with Farmer', 'Maharashtra', true),
                    ('Radio Talk with Farmer', 'Madhya Pradesh', true),
                    ('Radio Talk with Farmer', 'Uttar Pradesh', true),
                    ('Radio Talk with Farmer', 'Haryana', true),
                    ('Radio Talk with Farmer', 'Bihar', true),
                    ('Radio Talk with Farmer', 'West Bengal', true),
                    ('Filming Success story', 'Tamil Nadu', true),
                    ('Filming Success story', 'Karnataka', true),
                    ('Filming Success story', 'Kerala', true),
                    ('Filming Success story', 'Andhra Pradesh', true),
                    ('Filming Success story', 'Telangana', true),
                    ('Filming Success story', 'Maharashtra', true),
                    ('Filming Success story', 'Madhya Pradesh', true),
                    ('Filming Success story', 'Uttar Pradesh', true),
                    ('Filming Success story', 'Haryana', true),
                    ('Filming Success story', 'Bihar', true),
                    ('Filming Success story', 'West Bengal', true),
                    ('Wall/ Shop/ Trolley Painting', 'Tamil Nadu', true),
                    ('Wall/ Shop/ Trolley Painting', 'Karnataka', true),
                    ('Wall/ Shop/ Trolley Painting', 'Kerala', true),
                    ('Wall/ Shop/ Trolley Painting', 'Andhra Pradesh', true),
                    ('Wall/ Shop/ Trolley Painting', 'Telangana', true),
                    ('Wall/ Shop/ Trolley Painting', 'Maharashtra', true),
                    ('Wall/ Shop/ Trolley Painting', 'Madhya Pradesh', true),
                    ('Wall/ Shop/ Trolley Painting', 'Uttar Pradesh', true),
                    ('Wall/ Shop/ Trolley Painting', 'Haryana', true),
                    ('Wall/ Shop/ Trolley Painting', 'Bihar', true),
                    ('Wall/ Shop/ Trolley Painting', 'West Bengal', true),
                    ('Printing of Publicity Materials', 'Tamil Nadu', true),
                    ('Printing of Publicity Materials', 'Karnataka', true),
                    ('Printing of Publicity Materials', 'Kerala', true),
                    ('Printing of Publicity Materials', 'Andhra Pradesh', true),
                    ('Printing of Publicity Materials', 'Telangana', true),
                    ('Printing of Publicity Materials', 'Maharashtra', true),
                    ('Printing of Publicity Materials', 'Madhya Pradesh', true),
                    ('Printing of Publicity Materials', 'Uttar Pradesh', true),
                    ('Printing of Publicity Materials', 'Haryana', true),
                    ('Printing of Publicity Materials', 'Bihar', true),
                    ('Printing of Publicity Materials', 'West Bengal', true),
                    ('Giveaways', 'Tamil Nadu', true),
                    ('Giveaways', 'Karnataka', true),
                    ('Giveaways', 'Kerala', true),
                    ('Giveaways', 'Andhra Pradesh', true),
                    ('Giveaways', 'Telangana', true),
                    ('Giveaways', 'Maharashtra', true),
                    ('Giveaways', 'Madhya Pradesh', true),
                    ('Giveaways', 'Uttar Pradesh', true),
                    ('Giveaways', 'Haryana', true),
                    ('Giveaways', 'Bihar', true),
                    ('Giveaways', 'West Bengal', true),
                    ('Calendars/ Diaries', 'Tamil Nadu', true),
                    ('Calendars/ Diaries', 'Karnataka', true),
                    ('Calendars/ Diaries', 'Kerala', true),
                    ('Calendars/ Diaries', 'Andhra Pradesh', true),
                    ('Calendars/ Diaries', 'Telangana', true),
                    ('Calendars/ Diaries', 'Maharashtra', true),
                    ('Calendars/ Diaries', 'Madhya Pradesh', true),
                    ('Calendars/ Diaries', 'Uttar Pradesh', true),
                    ('Calendars/ Diaries', 'Haryana', true),
                    ('Calendars/ Diaries', 'Bihar', true),
                    ('Calendars/ Diaries', 'West Bengal', true),
                    ('Dealer Tour', 'Tamil Nadu', true),
                    ('Dealer Tour', 'Karnataka', false),
                    ('Dealer Tour', 'Kerala', false),
                    ('Dealer Tour', 'Andhra Pradesh', false),
                    ('Dealer Tour', 'Telangana', false),
                    ('Dealer Tour', 'Maharashtra', false),
                    ('Dealer Tour', 'Madhya Pradesh', false),
                    ('Dealer Tour', 'Uttar Pradesh', false),
                    ('Dealer Tour', 'Haryana', false),
                    ('Dealer Tour', 'Bihar', false),
                    ('Dealer Tour', 'West Bengal', false);

                DO $$
                DECLARE r record;
                BEGIN
                    FOR r IN
                        SELECT DISTINCT c.""ProgramName"" FROM ""_ProgramStateCsv"" c
                        WHERE NOT EXISTS (SELECT 1 FROM ""ProgramMasters"" p
                                          WHERE lower(trim(p.""Name"")) = lower(trim(c.""ProgramName"")))
                    LOOP
                        RAISE NOTICE 'ProgramStateMapping: CSV program not matched to ProgramMasters: %', r.""ProgramName"";
                    END LOOP;

                    FOR r IN
                        SELECT DISTINCT c.""StateName"" FROM ""_ProgramStateCsv"" c
                        WHERE NOT EXISTS (SELECT 1 FROM ""States"" s
                                          WHERE lower(trim(s.""StateName"")) = lower(trim(c.""StateName"")))
                    LOOP
                        RAISE NOTICE 'ProgramStateMapping: CSV state not matched to States: %', r.""StateName"";
                    END LOOP;
                END $$;

                INSERT INTO ""ProgramStateMappings"" (""ProgramId"", ""StateId"", ""IsApplicable"", ""CreatedBy"", ""UpdatedBy"", ""CreatedAt"", ""UpdatedAt"")
                SELECT p.""Id"", s.""Id"", c.""IsApplicable"", 'System', 'System', LOCALTIMESTAMP, LOCALTIMESTAMP
                FROM ""_ProgramStateCsv"" c
                JOIN ""ProgramMasters"" p ON lower(trim(p.""Name"")) = lower(trim(c.""ProgramName""))
                JOIN ""States"" s ON lower(trim(s.""StateName"")) = lower(trim(c.""StateName""))
                ON CONFLICT (""ProgramId"", ""StateId"") DO NOTHING;

                DROP TABLE IF EXISTS ""_ProgramStateCsv"";
            ");

            // Page key "ProgramMaster" (PagePermission, appended last) for the MD Portal Program
            // Master page. EF would scaffold InsertData with the enum-index id 122, but live
            // databases assign Pages ids differently (see V5t/v9). Same idempotent pattern as V5t:
            // insert by Key when missing with a generated id, never touch an existing row, then
            // move the sequence on.
            migrationBuilder.Sql(@"
SELECT setval(pg_get_serial_sequence('""Pages""', 'Id'), GREATEST((SELECT COALESCE(MAX(""Id""), 0) FROM ""Pages"") + 1, nextval(pg_get_serial_sequence('""Pages""', 'Id'))), false);
INSERT INTO ""Pages"" (""CreatedAt"",""CreatedBy"",""HasActions"",""IsActive"",""Key"",""Module"",""Name"",""SortOrder"",""UpdatedAt"",""UpdatedBy"")
SELECT TIMESTAMP '2024-01-01 00:00:00', 'System', TRUE, TRUE, 'ProgramMaster', NULL, 'Program Master', 121, TIMESTAMP '2024-01-01 00:00:00', 'System'
WHERE NOT EXISTS (SELECT 1 FROM ""Pages"" WHERE ""Key"" = 'ProgramMaster');
SELECT setval(pg_get_serial_sequence('""Pages""', 'Id'), GREATEST((SELECT COALESCE(MAX(""Id""), 0) FROM ""Pages"") + 1, nextval(pg_get_serial_sequence('""Pages""', 'Id'))), false);
");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {

            migrationBuilder.DropTable(
                name: "ProgramStateMappings");

            // The ProgramMaster Pages row is kept (harmless, and designations may already reference it).
        }
    }
}
