// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Spic.Infrastructure.Data;

#nullable disable

namespace Spic.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AppRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AppRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AppUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AppUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AppUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AppUserTokens", (string)null);
                });

            modelBuilder.Entity("SPIC.Core.Entities.AnnualSaleDataLastFYofDealerRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("DealerId")
                        .HasColumnType("integer");

                    b.Property<decimal>("OwnRetailsSaleAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OwnRetailsSaleQty")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<decimal>("SaleToDealerAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SaleToDealerQty")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("AnnualSaleDataLastFY");
                });

            modelBuilder.Entity("SPIC.Core.Entities.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("SPIC.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSpecialityProduct")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UnitId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("SPIC.Core.Entities.Competitor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Competitors");
                });

            modelBuilder.Entity("SPIC.Core.Entities.Crop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Crops");
                });

            modelBuilder.Entity("SPIC.Core.Entities.DealerApprovalHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ApprovedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ApprovedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("AvpCreditLimit")
                        .HasColumnType("numeric");

                    b.Property<int>("DealerId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("RmCreditLimit")
                        .HasColumnType("numeric");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("SmCreditLimit")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("DealerApprovalHistories");
                });

            modelBuilder.Entity("SPIC.Core.Entities.DealerAssetBank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BankBranch")
                        .HasColumnType("text");

                    b.Property<int>("BankId")
                        .HasColumnType("integer");

                    b.Property<int>("DealerId")
                        .HasColumnType("integer");

                    b.Property<string>("FileUploadPath")
                        .HasColumnType("text");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("DealerAssetBanks");
                });

            modelBuilder.Entity("SPIC.Core.Entities.DealerAssetBuilding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Block")
                        .HasColumnType("text");

                    b.Property<string>("BuildingName")
                        .HasColumnType("text");

                    b.Property<int>("DealerId")
                        .HasColumnType("integer");

                    b.Property<int>("DistrictId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("LandSize")
                        .HasColumnType("numeric");

                    b.Property<string>("PinCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PropertyValue")
                        .HasColumnType("numeric");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<string>("ShopNoORRoomNoOrBlockNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StateId")
                        .HasColumnType("integer");

                    b.Property<string>("Street")
                        .HasColumnType("text");

                    b.Property<string>("SubVillage")
                        .HasColumnType("text");

                    b.Property<string>("SurveyNumber")
                        .HasColumnType("text");

                    b.Property<string>("Taluk")
                        .HasColumnType("text");

                    b.Property<string>("UploadedBuildingDocumentPath")
                        .HasColumnType("text");

                    b.Property<string>("UploadedECDocumentPath")
                        .HasColumnType("text");

                    b.Property<string>("UploadedValuationCertificatePath")
                        .HasColumnType("text");

                    b.Property<string>("Village")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DealerAssetBuildings");
                });

            modelBuilder.Entity("SPIC.Core.Entities.DealerAssetLand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DealerId")
                        .HasColumnType("integer");

                    b.Property<string>("LandName")
                        .HasColumnType("text");

                    b.Property<decimal>("LandSize")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PropertyValue")
                        .HasColumnType("numeric");

                    b.Property<string>("SurvayNumber")
                        .HasColumnType("text");

                    b.Property<string>("UploadedECDocumentPath")
                        .HasColumnType("text");

                    b.Property<string>("UploadedLandDocumentPath")
                        .HasColumnType("text");

                    b.Property<string>("UploadedValuationCertificatePath")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DealerAssetLands");
                });

            modelBuilder.Entity("SPIC.Core.Entities.DealerCompaniesOperatingInArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompaniesOperating")
                        .HasColumnType("text");

                    b.Property<int>("DealerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("DealerCompaniesOperatingInAreas");
                });

            modelBuilder.Entity("SPIC.Core.Entities.DealerCreditLimitProposal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AdditionalCreditLimit")
                        .HasColumnType("numeric");

                    b.Property<int>("DealerId")
                        .HasColumnType("integer");

                    b.Property<int>("FY1")
                        .HasColumnType("integer");

                    b.Property<int>("FY2")
                        .HasColumnType("integer");

                    b.Property<int>("FY3")
                        .HasColumnType("integer");

                    b.Property<double>("GQ10Mark")
                        .HasColumnType("double precision");

                    b.Property<double>("GQ11Mark")
                        .HasColumnType("double precision");

                    b.Property<double>("GQ12Mark")
                        .HasColumnType("double precision");

                    b.Property<double>("GQ1Mark")
                        .HasColumnType("double precision");

                    b.Property<double>("GQ2Mark")
                        .HasColumnType("double precision");

                    b.Property<double>("GQ3Mark")
                        .HasColumnType("double precision");

                    b.Property<double>("GQ4Mark")
                        .HasColumnType("double precision");

                    b.Property<double>("GQ5Mark")
                        .HasColumnType("double precision");

                    b.Property<double>("GQ6Mark")
                        .HasColumnType("double precision");

                    b.Property<double>("GQ7Mark")
                        .HasColumnType("double precision");

                    b.Property<double>("GQ8Mark")
                        .HasColumnType("double precision");

                    b.Property<double>("GQ9Mark")
                        .HasColumnType("double precision");

                    b.Property<decimal>("GSExistingCreditLimitAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("GSExistingCreditLimitFrom")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("GSExistingCreditLimitTo")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("GreenstarAdditionalCreditLimit")
                        .HasColumnType("numeric");

                    b.Property<decimal>("GreenstarBGAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("GreenstarBGNumber")
                        .HasColumnType("text");

                    b.Property<string>("GreenstarBGOtherDetails")
                        .HasColumnType("text");

                    b.Property<decimal>("GreenstarCollateralAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("GreenstarCollateralNumber")
                        .HasColumnType("text");

                    b.Property<string>("GreenstarCollateralOtherDetails")
                        .HasColumnType("text");

                    b.Property<decimal>("GreenstarFDAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("GreenstarFDNumber")
                        .HasColumnType("text");

                    b.Property<string>("GreenstarFDOtherDetails")
                        .HasColumnType("text");

                    b.Property<decimal>("GreenstarTradeDepositAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("GreenstarTradeDepositNumber")
                        .HasColumnType("text");

                    b.Property<string>("GreenstarTradeDepositOtherDetails")
                        .HasColumnType("text");

                    b.Property<double>("Q10Mark")
                        .HasColumnType("double precision");

                    b.Property<double>("Q11Mark")
                        .HasColumnType("double precision");

                    b.Property<double>("Q1Mark")
                        .HasColumnType("double precision");

                    b.Property<double>("Q2Mark")
                        .HasColumnType("double precision");

                    b.Property<double>("Q3Mark")
                        .HasColumnType("double precision");

                    b.Property<double>("Q4Mark")
                        .HasColumnType("double precision");

                    b.Property<double>("Q5Mark")
                        .HasColumnType("double precision");

                    b.Property<double>("Q6Mark")
                        .HasColumnType("double precision");

                    b.Property<double>("Q7Mark")
                        .HasColumnType("double precision");

                    b.Property<double>("Q8Mark")
                        .HasColumnType("double precision");

                    b.Property<double>("Q9Mark")
                        .HasColumnType("double precision");

                    b.Property<decimal>("SpicBGAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("SpicBGNumber")
                        .HasColumnType("text");

                    b.Property<string>("SpicBGOtherDetails")
                        .HasColumnType("text");

                    b.Property<decimal>("SpicCollateralAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("SpicCollateralNumber")
                        .HasColumnType("text");

                    b.Property<string>("SpicCollateralOtherDetails")
                        .HasColumnType("text");

                    b.Property<decimal>("SpicExistingCreditLimitAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("SpicExistingCreditLimitFrom")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("SpicExistingCreditLimitTo")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("SpicFDAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("SpicFDNumber")
                        .HasColumnType("text");

                    b.Property<string>("SpicFDOtherDetails")
                        .HasColumnType("text");

                    b.Property<decimal>("SpicTradeDepositAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("SpicTradeDepositNumber")
                        .HasColumnType("text");

                    b.Property<string>("SpicTradeDepositOtherDetails")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DealerCreditLimitProposals");
                });

            modelBuilder.Entity("SPIC.Core.Entities.DealerCreditLimitSales", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("CustomerNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FinancialYearId")
                        .HasColumnType("integer");

                    b.Property<decimal>("GrossAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductGroupId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<int>("StateId")
                        .HasColumnType("integer");

                    b.Property<int>("SubGroupId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("DealerCreditLimitSalesData");
                });

            modelBuilder.Entity("SPIC.Core.Entities.DealerCreditLimitSalesPerformance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("CreditLimitId")
                        .HasColumnType("integer");

                    b.Property<decimal>("FY1Amount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FY1Qty")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FY2Amount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FY2Qty")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FY3Amount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FY3Qty")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("DealerCreditLimitSalesPerformances");
                });

            modelBuilder.Entity("SPIC.Core.Entities.DealerExperience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DealerId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("NoOfYears")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TurnOver")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("DealerExperiences");
                });

            modelBuilder.Entity("SPIC.Core.Entities.DealerLoanLiabilities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DealerId")
                        .HasColumnType("integer");

                    b.Property<string>("LoanSource")
                        .HasColumnType("text");

                    b.Property<decimal>("LoanValue")
                        .HasColumnType("numeric");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DealerLoanLiabilities");
                });

            modelBuilder.Entity("SPIC.Core.Entities.DealerMarketDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DealerId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCanal")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTank")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWell")
                        .HasColumnType("boolean");

                    b.Property<int>("MajorCrops")
                        .HasColumnType("integer");

                    b.Property<string>("NameOfBlock")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NoOfDealer")
                        .HasColumnType("integer");

                    b.Property<int>("NoOfFarmer")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonFromMonth")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonToMonth")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("DealerMarketDetails");
                });

            modelBuilder.Entity("SPIC.Core.Entities.DealerOwnershipInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AadhaarFilePath")
                        .HasColumnType("text");

                    b.Property<string>("AadhaarNumber")
                        .HasColumnType("text");

                    b.Property<string>("Block")
                        .HasColumnType("text");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DealerId")
                        .HasColumnType("integer");

                    b.Property<int>("DistrictId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<int>("MaritalStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PANFilePath")
                        .HasColumnType("text");

                    b.Property<string>("PANNumber")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PinCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProprietorImagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShopNoORRoomNoOrBlockNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StateId")
                        .HasColumnType("integer");

                    b.Property<string>("Street")
                        .HasColumnType("text");

                    b.Property<string>("SubVillage")
                        .HasColumnType("text");

                    b.Property<string>("Taluk")
                        .HasColumnType("text");

                    b.Property<string>("Village")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DealerOwnershipInfos");
                });

            modelBuilder.Entity("SPIC.Core.Entities.DealerPortFacilities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DealerId")
                        .HasColumnType("integer");

                    b.Property<double>("Distance")
                        .HasColumnType("double precision");

                    b.Property<double>("Freight")
                        .HasColumnType("double precision");

                    b.Property<int>("PortId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("DealerPortFacilities");
                });

            modelBuilder.Entity("SPIC.Core.Entities.DealerRailFacilities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DealerId")
                        .HasColumnType("integer");

                    b.Property<double>("Distance")
                        .HasColumnType("double precision");

                    b.Property<double>("Freight")
                        .HasColumnType("double precision");

                    b.Property<int>("RailFacilitiesId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("DealerRailFacilities");
                });

            modelBuilder.Entity("SPIC.Core.Entities.DealerRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("AVPApproved")
                        .HasColumnType("boolean");

                    b.Property<string>("AadhaarFilePath")
                        .HasColumnType("text");

                    b.Property<string>("AadhaarNumber")
                        .HasColumnType("text");

                    b.Property<string>("AccountHolderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AlternativeNumber")
                        .HasColumnType("text");

                    b.Property<decimal>("AssetValue")
                        .HasColumnType("numeric");

                    b.Property<int>("BankId")
                        .HasColumnType("integer");

                    b.Property<string>("Block")
                        .HasColumnType("text");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BusinessEntityType")
                        .HasColumnType("text");

                    b.Property<decimal>("CapitalInvestment")
                        .HasColumnType("numeric");

                    b.Property<string>("CapitalInvestmentRemarks")
                        .HasColumnType("text");

                    b.Property<decimal>("CashCreditLimit")
                        .HasColumnType("numeric");

                    b.Property<string>("CashCreditLimitRrmarks")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreditLimitExperiance")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateOfAppointment")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DealerCode")
                        .HasColumnType("text");

                    b.Property<int>("DealerStateId")
                        .HasColumnType("integer");

                    b.Property<decimal>("DebitorBalance")
                        .HasColumnType("numeric");

                    b.Property<int>("DistrictId")
                        .HasColumnType("integer");

                    b.Property<int?>("EntityType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExpectedOfficeAutomationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FinalApprovalDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FirmName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GSTFilePath")
                        .HasColumnType("text");

                    b.Property<string>("GSTNumber")
                        .HasColumnType("text");

                    b.Property<string>("GoogleMapURL")
                        .HasColumnType("text");

                    b.Property<string>("GreenStarCode")
                        .HasColumnType("text");

                    b.Property<int>("HQ")
                        .HasColumnType("integer");

                    b.Property<string>("IFSC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("InGreenStar")
                        .HasColumnType("boolean");

                    b.Property<bool>("InSpic")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDealer")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsFinalAmountSettled")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsLastTransactionIsSale")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOfficeAutomation")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSDWA")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastTransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("OfficialContactNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("OwnGodownCapacity")
                        .HasColumnType("numeric");

                    b.Property<string>("PANFilePath")
                        .HasColumnType("text");

                    b.Property<string>("PANNumber")
                        .HasColumnType("text");

                    b.Property<int>("ParentDealer")
                        .HasColumnType("integer");

                    b.Property<string>("PinCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("RMApproved")
                        .HasColumnType("boolean");

                    b.Property<int>("Region")
                        .HasColumnType("integer");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<decimal>("RentGodownCapacity")
                        .HasColumnType("numeric");

                    b.Property<string>("RetailFertilizerLicenseNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("RetailLicenseExpiryDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RetailLicenseFilePath")
                        .HasColumnType("text");

                    b.Property<string>("RetailmFMSCode")
                        .HasColumnType("text");

                    b.Property<bool?>("SMApproved")
                        .HasColumnType("boolean");

                    b.Property<string>("SPICCode")
                        .HasColumnType("text");

                    b.Property<decimal>("SettlementAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("SettlementDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ShopNoORRoomNoOrBlockNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StateId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Street")
                        .HasColumnType("text");

                    b.Property<string>("SubVillage")
                        .HasColumnType("text");

                    b.Property<string>("Taluk")
                        .HasColumnType("text");

                    b.Property<string>("TnCode")
                        .HasColumnType("text");

                    b.Property<decimal>("TradeDepositAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("TradeDepositDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TradeDepositReceiptNo")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserTableId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Village")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WhatsAppNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WholeSaleFertilizerLicenseNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("WholesaleLicenseExpiryDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("WholesaleLicenseFilePath")
                        .HasColumnType("text");

                    b.Property<string>("WholesalemFMSCode")
                        .HasColumnType("text");

                    b.Property<int>("YearsofExperiance")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("DealerRegistrations");
                });

            modelBuilder.Entity("SPIC.Core.Entities.DealerRegistrationDocuments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AffidavitFilePath")
                        .HasColumnType("text");

                    b.Property<string>("AuthorizationLetterFilePath")
                        .HasColumnType("text");

                    b.Property<string>("BankGauranteeFilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BoardReasolutionFilePath")
                        .HasColumnType("text");

                    b.Property<int>("DealerId")
                        .HasColumnType("integer");

                    b.Property<string>("DeedOfGuaranteeFilePath")
                        .HasColumnType("text");

                    b.Property<int>("FY1")
                        .HasColumnType("integer");

                    b.Property<string>("FY1ITReturnFilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FY2")
                        .HasColumnType("integer");

                    b.Property<string>("FY2ITReturnFilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GreenstarSpecimanFilePath")
                        .HasColumnType("text");

                    b.Property<string>("PartnershipDeadFilePath")
                        .HasColumnType("text");

                    b.Property<string>("RetailerListFilePath")
                        .HasColumnType("text");

                    b.Property<string>("SpecimanFilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ValuationCertificateFilePath")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DealerRegistrationDocuments");
                });

            modelBuilder.Entity("SPIC.Core.Entities.DealerWarehouseFacilities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DealerId")
                        .HasColumnType("integer");

                    b.Property<double>("Distance")
                        .HasColumnType("double precision");

                    b.Property<double>("Freight")
                        .HasColumnType("double precision");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("DealerWarehouseFacilities");
                });

            modelBuilder.Entity("SPIC.Core.Entities.Designation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Designations");
                });

            modelBuilder.Entity("SPIC.Core.Entities.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DistrictName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("StateId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("SPIC.Core.Entities.EmployeeRegistration+EmployeeInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OfficialPhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PersonalPhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EmployeeInformation");
                });

            modelBuilder.Entity("SPIC.Core.Entities.EmployeeRegistration+Employeelogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeInformationID")
                        .HasColumnType("integer");

                    b.Property<int>("HeadquartersId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("RegionId")
                        .HasColumnType("integer");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("StateId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ZoneId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Employeelogins");
                });

            modelBuilder.Entity("SPIC.Core.Entities.FinancialYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FinancialYears");
                });

            modelBuilder.Entity("SPIC.Core.Entities.Headquarter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("HeadquarterName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("RegionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("Headquarters");
                });

            modelBuilder.Entity("SPIC.Core.Entities.PartnerFamilyDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FamilyMemberName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Occupation")
                        .HasColumnType("text");

                    b.Property<int>("OwnershipPartnerId")
                        .HasColumnType("integer");

                    b.Property<int>("RelationshipId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PartnerFamilyDetails");
                });

            modelBuilder.Entity("SPIC.Core.Entities.PartnerOccupation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AnnualTurnover")
                        .HasColumnType("numeric");

                    b.Property<string>("NameofCompany")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OwnershipPartnerId")
                        .HasColumnType("integer");

                    b.Property<int>("SectorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PartnerOccupations");
                });

            modelBuilder.Entity("SPIC.Core.Entities.Port", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DistrictId")
                        .HasColumnType("integer");

                    b.Property<string>("GoogleURL")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StateId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("StateId");

                    b.ToTable("Ports");
                });

            modelBuilder.Entity("SPIC.Core.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("SPIC.Core.Entities.RackPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DistrictId")
                        .HasColumnType("integer");

                    b.Property<string>("GoogleURL")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RailwayCode")
                        .HasColumnType("text");

                    b.Property<int>("StateId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("StateId");

                    b.ToTable("RackPoints");
                });

            modelBuilder.Entity("SPIC.Core.Entities.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StateId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("SPIC.Core.Entities.Relationship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Relationships");
                });

            modelBuilder.Entity("SPIC.Core.Entities.SalesPlanningInDealerRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AprilAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AprilQty")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AugustAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AugustQty")
                        .HasColumnType("numeric");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("DealerId")
                        .HasColumnType("integer");

                    b.Property<decimal>("DecemberAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DecemberQty")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FebruaryAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FebruaryQty")
                        .HasColumnType("numeric");

                    b.Property<decimal>("JanuaryAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("JanuaryQty")
                        .HasColumnType("numeric");

                    b.Property<decimal>("JulyAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("JulyQty")
                        .HasColumnType("numeric");

                    b.Property<decimal>("JuneAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("JuneQty")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MarchAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MarchQty")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MayAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MayQty")
                        .HasColumnType("numeric");

                    b.Property<decimal>("NovemberAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("NovemberQty")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OctoberAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OctoberQty")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<decimal>("SeptemberAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SeptemberQty")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("SalesPlannings");
                });

            modelBuilder.Entity("SPIC.Core.Entities.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Sectors");
                });

            modelBuilder.Entity("SPIC.Core.Entities.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ZoneId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId");

                    b.ToTable("States");
                });

            modelBuilder.Entity("SPIC.Core.Entities.SubDistrict", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DistrictId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("SubDistrictName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.ToTable("SubDistricts");
                });

            modelBuilder.Entity("SPIC.Core.Entities.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("SPIC.Core.Entities.UserInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int?>("DesignationId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("DesignationId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AppUsers", (string)null);
                });

            modelBuilder.Entity("SPIC.Core.Entities.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("GoogleURL")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WarehouseCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("SPIC.Core.Entities.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ZoneCode")
                        .HasColumnType("text");

                    b.Property<string>("ZoneColorCode")
                        .HasColumnType("text");

                    b.Property<string>("ZoneName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SPIC.Core.Entities.UserInfo", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SPIC.Core.Entities.UserInfo", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SPIC.Core.Entities.UserInfo", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SPIC.Core.Entities.UserInfo", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SPIC.Core.Entities.Category", b =>
                {
                    b.HasOne("SPIC.Core.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("SPIC.Core.Entities.District", b =>
                {
                    b.HasOne("SPIC.Core.Entities.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("SPIC.Core.Entities.Headquarter", b =>
                {
                    b.HasOne("SPIC.Core.Entities.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("SPIC.Core.Entities.Port", b =>
                {
                    b.HasOne("SPIC.Core.Entities.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SPIC.Core.Entities.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");

                    b.Navigation("State");
                });

            modelBuilder.Entity("SPIC.Core.Entities.Product", b =>
                {
                    b.HasOne("SPIC.Core.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SPIC.Core.Entities.RackPoint", b =>
                {
                    b.HasOne("SPIC.Core.Entities.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SPIC.Core.Entities.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");

                    b.Navigation("State");
                });

            modelBuilder.Entity("SPIC.Core.Entities.Region", b =>
                {
                    b.HasOne("SPIC.Core.Entities.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("SPIC.Core.Entities.State", b =>
                {
                    b.HasOne("SPIC.Core.Entities.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("SPIC.Core.Entities.SubDistrict", b =>
                {
                    b.HasOne("SPIC.Core.Entities.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("SPIC.Core.Entities.UserInfo", b =>
                {
                    b.HasOne("SPIC.Core.Entities.Designation", "Designation")
                        .WithMany()
                        .HasForeignKey("DesignationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Designation");
                });
#pragma warning restore 612, 618
        }
    }
}
